### ISSUE TITLE
Documented walkthrough on how to programmatically use Capistrano in Ruby

### ISSUE THREAD

**Issue by ezekg** [capistrano/documentation#131] opened 2015-03-23 20:54 UTC
_Moving this from the [original issue](https://github.com/capistrano/capistrano/issues/1403#issuecomment-84855036), since it's related to documentation._

----

The documentation [on this topic](http://capistranorb.com/documentation/advanced-features/capistrano-pure-ruby/) seems out of date, or incorrect. The example code given does not work correctly. Can we get a more thorough explanation of which files to `require` (and in what order,) as well as which methods to use to set a deployment config and initiate a deploy from within a Ruby script?

I'm trying to integrate Capistrano into an existing command line application, with configuration kept in a Yaml file, and have run into numerous issues trying to configure Capistrano to actually run without the typical `deploy.rb` and `Capfile` setup. It seems like it can't find any default tasks.

There just doesn't seem to be a clear API to allow something like this, yet the documentation above hints that it should be possible. Any advice on getting a little more up to speed on the _correct_ way to do something like this?

**Comment by will-in-wi** [comment] 2016-01-18 13:23
This may be a duplicate of https://github.com/capistrano/documentation/issues/107

**Comment by mattbrictson** [comment] 2016-01-18 19:31
Closing as dupe of #107.

**Closed by mattbrictson** 2016-01-18 19:31 UTC
